local config = {
    Enabled = true,
    IncantationsEnabled = {
        Apollo = true,
        Aphrodite = true,
        Arachne = true,
        Artemis = true,
        Athena = true,
        Charon = true,
        Chaos = true,
        Circe = true,
        Demeter = true,
        Dionysus = true,
        Dora = true,
        Echo = true,
        Eris = true,
        Hecate = true,
        Hera = true,
        Hephaestus = true,
        Heracles = true,
        Hermes = true,
        Icarus = true,
        Narcissus = true,
        Nemesis = true,
        Olympus = true,
        Poseidon = true,
        Schelemeus = true,
        Selene = true,
        Zeus = true,
    },
}

local description = {
    Enabled = "If false, the mod does nothing",
    IncantationsEnabled = {
        Apollo = "Enable Apollo's cast circle size incantation",
        Aphrodite = "Enable Aphrodite's nectar refund incantation",
        Arachne = "Enable Arachne's armor boost incantation",
        Artemis = "Enable Artemis' encounter boost incantation",
        Athena = "Enable Athena's encounter boost incantation",
        Charon = "Enable Charon's gold drops incantation",
        Chaos = "Enable Chaos' free reroll incantation",
        Circe = "Enable Circe's familiar minigames incantation",
        Demeter = "Enable Demeter's plant harvest incantations",
        Dionysus = "Enable Dionysus' nectar chance incantation",
        Dora = "Enable Dora's shade damage incantation",
        Echo = "Enable Echo's shop respawn incantation",
        Eris = "Enable Eris' rubbish selling incantation",
        Hecate = "Enable Hecate's starting mana incantation",
        Hera = "Enable Hera's elemental gift incantation",
        Hephaestus = "Enable Hephaestus' ore harvest incantations",
        Heracles = "Enable Heracles' challenge reward incantation",
        Hermes = "Enable Hermes' dodge boost incantation",
        Icarus = "Enable Icarus' encounter boost incantation",
        Narcissus = "Enable Narcissus' max HP incantation",
        Nemesis = "Enable Nemesis' challenge reward incantation",
        Olympus = "Enable Olympus' secret incantation",
        Poseidon = "Enable Poseidon's rare fish incantation",
        Schelemeus = "Enable Schelemeus' damage bones incantation",
        Selene = "Enable Selene's card upgrades incantation",
        Zeus = "Enable Zeus' Olympian damage boost incantation",
    },
}

return config, description